### ISSUE TITLE
The jsdoc format of referencing a var as a type supported by the plugin

### ISSUE THREAD

**Issue by klesun** [klesun/deep-js-completion#10]
Even though native [jsdoc format](http://usejsdoc.org/tags-type.html) is pretty useful itself [compared to some other languages](https://github.com/phpDocumentor/phpDocumentor2/issues/650#issuecomment-341051932), it still lacks one vital feature - _an ability to specify type that references some other var in your code_. The plugin adds that feature with the `=` format, like this:
```javascript
let makeBilling = () => ({
    ccVendor: 'visa',
    ccNumber: '4111111111111111',
    expirationDate: '08/19',
});

/** @param billing = makeBilling() */
let processBilling = (billing) => {
    billing.e;
};
```
![image](https://user-images.githubusercontent.com/5202330/51945868-862e8c00-2428-11e9-8a1e-0db85d47fb3e.png)

You can specify type of function argument with `@param` or declared variable with either `@var` or `@type`. You can also reference any var defined in other file with `at('FileName.js').varName`:
```javascript
/** @type params = {
 *     form: at('RbsClient.js').formParams,
 *     protocol: 'IQ JSON RPC',
 * } */
let params = await readPost();
```
![image](https://user-images.githubusercontent.com/5202330/51948432-21c3fa80-2431-11e9-87ec-ad8a92a96067.png)

You can type any valid javascript expression after the `=` (for example `await` to get type of `T` from `Promise<T>`):
```javascript
/**
 * @var person = {
 *     name: 'Vasya Pupkin',
 *     contacts: await at('RbsClient.js').whenContacts,
 * }
 */
let person = getCachedPerson();
```
![image](https://user-images.githubusercontent.com/5202330/51949881-0fe55600-2437-11e9-9d30-48a453782491.png)

**Comment by giladbarnea** [comment]
Thank you, this feature is really useful.
