### ISSUE TITLE
Stripped class names completion

### ISSUE THREAD

**Issue by brxkensmile** [klesun/deep-js-completion#15]
Dear @klesun,

Default JetBrains completion suggests only those classes, that were written with camel case (or replaces stripped class name with camel case, **but only to suggest in completion** (img.1 and 2) )

![img1](https://user-images.githubusercontent.com/5941219/69415496-69e43e80-0d1d-11ea-9e4f-0ce76a0c24b3.png)

![img2](https://user-images.githubusercontent.com/5941219/69415532-76689700-0d1d-11ea-985c-e43d966629f6.png)

It really would be nice to have "stripped" class names completion from .css/.scss/.less files.

Hope you understand what I meant. Thanks! :D

**Comment by klesun** [comment]
Hi. Sorry, I'm most likely not doing this due to lack of time and not seeing much future for the plugin, as typescript is becoming a def-facto environment everywhere nowadays.
